# Site Settings
locale: "ko-KR"
title: "lovely_dickho"
title_separator: "-"
name: "lovely_dickho"
description: "Philosophy, Mathematics, and Economics"
url: "https://lovely-dickho.github.io"
baseurl: ""
repository: "lovely-dickho/lovely-dickho.github.io"

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Author
author:
  name: "lovely_dickho"
  avatar: "https://github.com/lovely-dickho.png"
  bio: "Philosophy, Mathematics, and Economics"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:jaeyoung.seo1128@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lovely-dickho"

# Pagination
paginate: 5
paginate_path: /page:num/

# Markdown & Highlighter
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-toc

# Exclude
exclude:
  - LICENSE
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/

# Custom Variables
custom_tag_order: "일반균형, 후생경제학, 미시경제학, 계량경제학"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      mathjax: true