title: "lovely_dickho"
description: "Philosophy, Mathematics, and Economics"
url: "https://lovely-dickho.github.io"
baseurl: ""

# 원격 테마 적용
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# 프로필 설정
author:
  name: "Jae Young Seo"
  avatar: "https://github.com/lovely-dickho.png"
  bio: "Philosophy, Mathematics, and Economics"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:jaeyoung.seo1128@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lovely-dickho"

# 댓글 기능 설정 (Disqus)
comments:
  provider: "disqus"
  disqus:
    shortname: "본인의_disqus_shortname_입력" # 예: lovely-dickho

# 마크다운 및 플러그인 설정
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

paginate: 5
paginate_path: /page:num/

# 일반 포스트 기본 레이아웃, 수식(MathJax), 댓글 활성화
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      mathjax: true
      author_profile: true
      comments: true